import { useState } from 'react';
import type { DecisionAction, ExtractedField } from '../../domain/types';

export function DecisionControls({ field, hasDecision, busy, onSubmit }: { field: ExtractedField; hasDecision: boolean; busy: boolean; onSubmit: (action: DecisionAction, value?: string) => Promise<void> }) {
  const [changing, setChanging] = useState(false), [editing, setEditing] = useState<DecisionAction | null>(null), [value, setValue] = useState(''), [error, setError] = useState('');
  const submit = async (action: DecisionAction, nextValue?: string) => { setError(''); try { await onSubmit(action, nextValue); setEditing(null); setChanging(false); setValue(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Decision could not be saved.'); } };
  if (editing) return <form className="decision-form" onSubmit={(event) => { event.preventDefault(); void submit(editing, value); }}><label htmlFor={`${field.id}-${editing}`}>{editing === 'correct' ? 'Corrected value' : 'Your overriding value'}</label><input id={`${field.id}-${editing}`} autoFocus value={value} onChange={(event) => setValue(event.target.value)} required /><p className="help">{editing === 'correct' ? 'The field is right; fix its extracted value.' : 'Reject the agent’s conclusion and supply yours.'}</p>{error && <p className="inline-error" role="alert">{error}</p>}<div className="actions"><button className="primary" disabled={busy}>Save {editing}</button><button type="button" className="secondary" onClick={() => { setEditing(null); setError(''); }}>Cancel</button></div></form>;
  if (hasDecision && !changing) return <button className="change-decision" disabled={busy} onClick={() => setChanging(true)}>Change decision</button>;
  return <div className={hasDecision ? 'change-actions' : ''}><div className="actions" aria-label={`Review ${field.label}`}><button className="primary" disabled={busy} onClick={() => void submit('accept')}>Accept</button><button className="secondary" disabled={busy} onClick={() => setEditing('correct')}>Correct</button><button className="secondary" disabled={busy} onClick={() => setEditing('override')}>Override</button>{hasDecision && <button className="quiet" disabled={busy} onClick={() => setChanging(false)}>Keep current decision</button>}</div>{error && <p className="inline-error" role="alert">{error}</p>}</div>;
}
